import assert from 'node:assert/strict'
import { existsSync } from 'node:fs'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

test('主进程安装全局异常兜底并复用统一退出清理', async () => {
  const source = await readFile(new URL('../../src/main.ts', import.meta.url), 'utf8')
  assert.match(source, /process\.on\('uncaughtException'/)
  assert.match(source, /process\.on\('unhandledRejection'/)
  assert.match(source, /async function shutdownDesktop/)
  assert.equal((source.match(/quitDesktopApp\(/g) ?? []).length, 1)
})

test('缺少离线 store 时仍执行官方清理和补种入口', async () => {
  const source = await readFile(new URL('../../src/main.ts', import.meta.url), 'utf8')
  assert.doesNotMatch(source, /if \(pluginStoreDir !== undefined\) \{\s*try \{\s*const seeded = await seedBundledPlugins/)
})

test('主窗口导航完成前不结束启动或插件热重载', async () => {
  const source = await readFile(new URL('../../src/main.ts', import.meta.url), 'utf8')
  assert.equal((source.match(/await createMainWindow\(server\.url\)/g) ?? []).length, 2)
  assert.match(source, /isRecycling = true\s+broadcastShellState\(\)\s+try \{\s+await showStartupWindow\(desktopText\('加载中', 'Loading'\)\)/)
  assert.match(source, /console\.error\('显示启动错误页面失败。'/)
  assert.match(source, /will-navigate'[\s\S]*?windowNavigation\.isNavigating\(\)[\s\S]*?event\.preventDefault\(\)/)
  assert.match(source, /watchProfileActivation\(profileDir, scheduleProfileActivationRecycle/)
  assert.match(source, /waitForDshMarketBatchToSettle\(/)
  assert.match(source, /function handleDshIpc\(message: unknown\): void \{[\s\S]*?scheduleProfileActivationRecycle\(\)/)
  assert.match(source, /profileActivationRecycleGeneration !== generation\) continue/)
  assert.match(source, /escapeRoute\(/)
  assert.doesNotMatch(source, /contents === dshView\?\.webContents \|\| contents === mainWindow\?\.webContents/)
  assert.match(source, /dshSettingsDialogVisible/)
  assert.match(source, /\[role=\"dialog\"\]\[aria-modal=\"true\"\]/)
  assert.match(source, /\^\(设置\|settings\)\$/)
  assert.match(source, /dismissDshSettingsDialog\(\)/)
  assert.match(source, /DSH_MARKET_BATCH_MAX_WAIT_MS/)
})

test('桌面壳与 DSH 内容分层并复用托盘重载实现', async () => {
  const source = await readFile(new URL('../../src/main.ts', import.meta.url), 'utf8')
  assert.match(source, /new WebContentsView/)
  assert.match(source, /window\.contentView\.addChildView\(view\)/)
  assert.match(source, /id === 'reload'\) await recycleDshForPluginUpdate\(\)/)
  assert.match(source, /if \(id === 'reload'\) \{\s+await recycleDshForPluginUpdate\(\)/)
  assert.match(source, /title: DESKTOP_APP_NAME/)
  assert.match(source, /partition: DSH_PARTITION/)
  assert.match(source, /await clearStaleDshAuthCookies\(view\.webContents\.session\.cookies, serverUrl\)/)
})

test('桌面壳预加载脚本被编译并提供 DSH 动作兜底', async () => {
  const config = await readFile(new URL('../../tsconfig.json', import.meta.url), 'utf8')
  const preload = await readFile(new URL('../../src/dsh-view-preload.cts', import.meta.url), 'utf8')
  assert.match(config, /src\/\*\*\/\*\.cts/)
  assert.match(preload, /clientBridgeRegistrations/)
  assert.match(preload, /runDomAction/)
  assert.match(preload, /添加工作区\|打开文件夹/)
  assert.match(preload, /\.dcu-wb-session\[role="treeitem"\]\[aria-selected\]/)
  assert.match(preload, /\^新建任务\$/)
})

test('桌面菜单使用窗口内坐标且 DSH 客户端桥接导出标准插件入口', async () => {
  const main = await readFile(new URL('../../src/main.ts', import.meta.url), 'utf8')
  const bridge = await readFile(new URL('../../src/desktop-bridge-client-source.ts', import.meta.url), 'utf8')
  const dshPreload = await readFile(new URL('../../src/dsh-view-preload.cts', import.meta.url), 'utf8')
  assert.match(main, /x: Math\.round\(request\.x\),\s+y: Math\.round\(request\.y\)/)
  assert.doesNotMatch(main, /contentBounds\.x \+ Math\.round\(request\.x\)/)
  assert.match(bridge, /window\.__ModuleLoader__\.load/)
  assert.match(bridge, /const inject/)
  assert.match(bridge, /const apply/)
  assert.match(bridge, /ctx\.workspaces\.startSession\(\)/)
})

test('关于窗口使用独立丰富页面并进入打包资源', async () => {
  const main = await readFile(new URL('../../src/main.ts', import.meta.url), 'utf8')
  const manifest = await readFile(new URL('../../package.json', import.meta.url), 'utf8')
  const about = await readFile(new URL('../../assets/about.html', import.meta.url), 'utf8')
  assert.match(main, /showAboutWindow\(\)/)
  assert.match(manifest, /assets\/about\.html/)
  assert.match(about, /关于这个项目/)
  assert.match(about, /runtimeVersion/)
  assert.match(about, /bundledRuntimeVersion/)
  assert.match(about, /runtimeUpdateChannel/)
  assert.match(main, /runtimeVersion: runningDshRuntimeVersion\(\)/)
  assert.match(main, /bundledRuntimeVersion: OFFICIAL_DSH_VERSION/)
  assert.match(main, /runtimeUpdateChannel: harnessUpdatePolicy\.channel/)
  assert.match(about, /overflow:hidden/)
  assert.match(main, /resizable: false/)
  assert.match(main, /frame: false/)
  assert.match(main, /minimizable: false/)
  assert.match(main, /maximizable: false/)
})

test('桌面通知和更新设置使用独立窗口并进入打包资源', async () => {
  const main = await readFile(new URL('../../src/main.ts', import.meta.url), 'utf8')
  const manifest = await readFile(new URL('../../package.json', import.meta.url), 'utf8')
  const settings = await readFile(new URL('../../assets/settings.html', import.meta.url), 'utf8')
  assert.match(main, /showDesktopSettingsWindow\(\)/)
  assert.match(main, /new Notification\(/)
  assert.match(main, /ensureWindowsNotificationIdentity\(\)/)
  assert.match(main, /setToastActivatorCLSID/)
  assert.match(main, /toastActivatorClsid:/)
  assert.match(main, /hasReply: true/)
  assert.match(main, /buildWindowsReplyToastXml/)
  assert.match(main, /Notification\.handleActivation/)
  assert.match(main, /parseWindowsNotificationReplyActivation/)
  assert.match(main, /replyArguments: windowsNotificationReplyArguments\(event\.sessionId\)/)
  assert.match(main, /replyLabel: zh \? '回复' : 'Reply'/)
  assert.match(main, /`\$\{status\} · \$\{event\.title\}`/)
  assert.match(main, /supportsReply && process\.platform !== 'win32'/)
  assert.match(main, /writeShortcutLink\(/)
  assert.match(main, /setOverlayIcon\(/)
  assert.match(manifest, /assets\/settings\.html/)
  assert.match(manifest, /assets\/task-badges/)
  assert.match(settings, /任务完成通知/)
  assert.match(settings, /approvalsEnabled/)
  assert.match(settings, /questionsEnabled/)
  assert.match(settings, /role="listbox"/)
  assert.match(settings, /class="select-menu"/)
  assert.doesNotMatch(settings, /<select/)
  assert.match(main, /mayReportDshLocale/)
  assert.match(main, /broadcastShellBootstrap/)
  assert.match(settings, /api\.onBootstrap/)
  assert.match(settings, /id="updatesNav"/)
  assert.match(settings, /id="updatesPage"/)
  assert.match(settings, /data-value="notify"/)
  assert.match(settings, /data-value="auto-download"/)
  assert.match(settings, /data-value="manual"/)
  assert.match(settings, /api\.updateUpdatePreferences/)
  assert.match(settings, /api\.desktopUpdateAction/)
  assert.match(settings, /api\.closeDesktopSettings/)
  assert.match(main, /SHELL_IPC\.closeDesktopSettings/)
  assert.match(settings, /api\.onDesktopUpdateState/)
  assert.match(settings, /安装前始终由你确认/)
  assert.match(settings, /Installation always requires your confirmation/)
  assert.match(main, /showDesktopSettingsWindow\('updates'\)/)
  assert.match(main, /PortableDesktopUpdater/)
  assert.match(main, /stageActivation\(\)/)
  assert.match(main, /preserveDesktopUpdateFailure/)
  assert.doesNotMatch(main, /checked\.phase === 'error'\) throw/)
  assert.doesNotMatch(main, /prepared\.phase === 'error'\) throw/)
  assert.match(settings, /错误码：/)
  assert.match(settings, /status\.transactionId/)
  assert.doesNotMatch(main, /autoUpdater|electron-updater/)
  assert.match(main, /function removeNativeWindowMenu/)
  assert.match(main, /window\.setMenu\(null\)/)
  assert.match(main, /window\.setMenuBarVisibility\(false\)/)
  assert.equal((main.match(/removeNativeWindowMenu\(window\)/g) ?? []).length, 4)
})

test('shell 在 macOS 为交通灯预留空间且状态早到不会读取空 bootstrap', async () => {
  const shell = await readFile(new URL('../../assets/shell.html', import.meta.url), 'utf8')
  assert.match(shell, /data-platform="darwin"[^}]*padding-left:78px/)
  assert.ok(shell.indexOf('document.documentElement.dataset.platform=window.dshShell.platform') < shell.indexOf('<style>'))
  assert.match(shell, /bootstrap\?\.locale/)
  assert.match(shell, /state\?\?value\.state/)
})

test('顶栏移除重复浏览器入口且重启确认保持紧凑图标态', async () => {
  const main = await readFile(new URL('../../src/main.ts', import.meta.url), 'utf8')
  const shell = await readFile(new URL('../../assets/shell.html', import.meta.url), 'utf8')
  assert.doesNotMatch(shell, /id="home-btn"/)
  assert.doesNotMatch(shell, /browser-toggle/)
  assert.doesNotMatch(shell, /confirm-text/)
  // 2026-09-13 用户改版拍板：重启并入右段工具组（「必须是最左第一个」是上一轮的布局决定，已被覆盖）。
  // 保护意图不变——全壳唯一一个重启入口、紧凑图标态、两步确认与拒绝文案仍在。
  const barLeft = shell.slice(shell.indexOf('<div class="bar-left">'), shell.indexOf('<div class="bar-right">'))
  const barRight = shell.slice(shell.indexOf('<div class="bar-right">'), shell.indexOf('</header>'))
  assert.match(barLeft, /<div class="bar-left">\s*<button id="back"/)
  assert.doesNotMatch(barLeft, /id="restart-btn"/)
  assert.match(barRight, /id="restart-btn"[\s\S]*shell-icons\/power\.svg/)
  assert.equal((shell.match(/id="restart-btn"/g) ?? []).length, 1)
  // 同一轮拍板的中段方案 A（居中定宽 320）也钉住，防止静默退回隐藏态
  assert.match(shell, /\.command-center\{position:absolute;left:50%;top:50%;transform:translate\(-50%,-50%\)[^}]*width:320px/)
  assert.match(shell, /restartConfirming\?\(zh\?'再次点击重启·Esc 取消'/)
  assert.match(shell, /restartBtn\.setAttribute\('aria-pressed','true'\)/)
  assert.match(main, /async function spawnPortableLauncherForRestart\(\)/)
  assert.match(main, /'-File', launcherScript, '-WaitForProcessId', String\(process\.pid\), '-HandoffReadyFile', handoffReadyFile/)
  assert.match(main, /const handoffDeadline = Date\.now\(\) \+ 10_000/)
  assert.match(main, /join\(windowsRoot, 'System32', 'WindowsPowerShell', 'v1\.0', 'powershell\.exe'\)/)
  assert.match(main, /join\(windowsRoot, 'System32', 'cmd\.exe'\)/)
  assert.match(main, /spawn\(commandBrokerExecutable/)
  assert.match(main, /'\/d', '\/s', '\/c', 'start', '', '\/b', powerShellExecutable/)
  const handoffSpawnStart = main.indexOf('const child = spawn(commandBrokerExecutable')
  const handoffSpawnEnd = main.indexOf('await new Promise<void>', handoffSpawnStart)
  assert.ok(handoffSpawnStart >= 0 && handoffSpawnEnd > handoffSpawnStart)
  assert.doesNotMatch(main.slice(handoffSpawnStart, handoffSpawnEnd), /detached: true/)
  assert.match(main, /while \(!existsSync\(handoffReadyFile\)\)/)
  assert.match(main, /等待便携启动器接管超时/)
  assert.match(main, /unlinkSync\(handoffReadyFile\)/)
  assert.match(main, /restart-handoff\.log/)
  assert.match(main, /appendFileSync\(restartAuditPath/)
  assert.match(main, /if \(portablePaths !== undefined && process\.platform === 'win32'\) \{\s+try \{\s+await spawnPortableLauncherForRestart\(\)/)
  assert.match(main, /if \(!await scheduleAppRelaunch\(\)\)/)
})

test('侧栏保留原宽度约束，顶部不恢复重复开关', async () => {
  const shell = await readFile(new URL('../../assets/shell.html', import.meta.url), 'utf8')
  const theme = await readFile(new URL('../../assets/theme.css', import.meta.url), 'utf8')
  const dshPreload = await readFile(new URL('../../src/dsh-view-preload.cts', import.meta.url), 'utf8')
  const workbench = await readFile(new URL('../../Customize/Automation-Workbench/workbench.js', import.meta.url), 'utf8')
  assert.doesNotMatch(shell, /id="home-panel"|data-action="toggle-sidebar"/)
  const actions = await readFile(new URL('../../src/shell-actions.ts', import.meta.url), 'utf8')
  assert.match(actions, /id: 'toggle-sidebar'.*CmdOrCtrl\+B/)
  assert.match(shell, /id="workspace-label"[^>]*data-action="home"/)
  assert.match(theme, /body \.dcu-root,\s*body \.dcu-foot\s*\{\s*width: 252px !important/)
  assert.match(theme, /body \[data-side="sidebar"\]\s*\{\s*display: none !important/)
  assert.match(dshPreload, /const SIDEBAR_MAX_WIDTH = 252/)
  assert.match(workbench, /\.daw-page\{position:fixed;inset:0 0 0 252px/)
})

test('第一套全功能浏览器原位接入 DSH 浏览器 Tab 且不压缩主内容区', async () => {
  const main = await readFile(new URL('../../src/main.ts', import.meta.url), 'utf8')
  const panel = await readFile(new URL('../../assets/browser-panel.html', import.meta.url), 'utf8')
  const workspace = await readFile(new URL('../../assets/browser-workspace.js', import.meta.url), 'utf8')
  const workspaceStyles = await readFile(new URL('../../assets/browser-workspace.css', import.meta.url), 'utf8')
  const dshPreload = await readFile(new URL('../../src/dsh-view-preload.cts', import.meta.url), 'utf8')
  const manifest = JSON.parse(await readFile(new URL('../../package.json', import.meta.url), 'utf8')) as {
    build?: { extraResources?: Array<{ from?: string; to?: string }> }
  }
  for (const id of ['browser-manager', 'browser-download-drawer', 'browser-find', 'browser-credential-form', 'browser-extension-list']) {
    assert.match(panel, new RegExp(`id="${id}"`))
  }
  for (const capability of ['importProfile', 'bookmarkCurrent', 'autofillPage', 'captureScreenshot', 'checkRuntime']) {
    assert.match(workspace, new RegExp(`browser\\.${capability}`))
  }
  assert.match(main, /完整移植自 G:\\DSH-Portable/)
  assert.match(main, /setSavePath\(destination\)/)
  assert.match(main, /credential\.origin !== pageOrigin/)
  assert.match(dshPreload, /browserPanel:\s*\{/)
  assert.match(dshPreload, /reportBounds:\s*\(bounds: unknown\)/)
  assert.match(main, /mayManageBrowserPanel\(shellRendererKind\(event\.sender\)\)/)
  assert.match(main, /dshView\?\.setBounds\(\{ x: 0, y: SHELL_BAR_HEIGHT, width: bounds\.width/)
  assert.doesNotMatch(main, /dshView\?\.setVisible\(!browserMaximized\)/)
  assert.match(main, /chrome\.capturePage\(\)/)
  assert.match(main, /active\.capturePage\(\)/)
  assert.match(main, /SHELL_IPC\.browserPanelPrepareOcclusion/)
  assert.match(main, /SHELL_IPC\.browserPanelOccluded/)
  assert.match(main, /SHELL_IPC\.browserPrepareMenuSnapshot/)
  assert.match(main, /if \(image\.isEmpty\(\)\) return null/)
  assert.match(workspace, /await browser\.prepareMenuSnapshot\(\)/)
  assert.ok(workspace.indexOf('await pageSnapshot.decode()') < workspace.indexOf('await browser.toggleMenu(true)'))
  assert.ok(workspace.indexOf('await nextPaint();\n      await nextPaint();') < workspace.indexOf('await browser.toggleMenu(true)'))
  assert.match(workspace, /当前网页快照不可用，已保留原生网页/)
  assert.match(workspaceStyles, /\.browser img\.browser-page-snapshot\{[^}]*width:100%[^}]*filter:none[^}]*opacity:1/)
  assert.match(workspaceStyles, /:root\[data-color-scheme="light"\] \.browser img\.browser-page-snapshot\{filter:none;opacity:1\}/)
  assert.match(panel, /\.browser-tabs-list\{[^}]*max-width:calc\(100% - 36px\)[^}]*flex:0 1 auto/)
  assert.match(panel, /\.browser-tabs-actions\{[^}]*margin:0 auto 0 0/)
  assert.match(panel, /\.browser-tabs \.tab\.active::after\{[^}]*background:var\(--browser-accent\)/)
  assert.match(panel, /\.browser-tabs \.tab:not\(\.active\):not\(:hover\) \.tab-close\{opacity:0\}/)
  assert.match(panel, /\.browser-nav input:focus\{[^}]*box-shadow:0 0 0 2px/)
  assert.doesNotMatch(await readFile(new URL('../../src/shell-actions.ts', import.meta.url), 'utf8'), /id:\s*'browser-toggle'/)
  assert.match(workspaceStyles, /container-type:inline-size/)
  assert.match(workspaceStyles, /@container browser-workspace \(min-width:760px\)/)
  assert.match(main, /resolveBrowserDownloadsDrawerHeight\(browserDownloadsOpen, browserDownloads\.length, panel\.height\)/)
  assert.match(workspace, /state\.downloadsDrawerHeight/)
  assert.match(workspaceStyles, /color:var\(--browser-text\)/)
  assert.match(workspaceStyles, /height:var\(--browser-downloads-height,112px\)/)
  assert.match(panel, /class="browser-drawer-copy"/)
  assert.match(panel, /class="browser-manager-copy"/)
  for (const asset of ['assets/browser-panel.html', 'assets/browser-workspace.css', 'assets/browser-workspace.js']) {
    assert.ok(manifest.build?.extraResources?.some(item => item.from === asset))
  }
})

test('原生菜单关闭后才清理外壳菜单的选中状态', async () => {
  const main = await readFile(new URL('../../src/main.ts', import.meta.url), 'utf8')
  const shell = await readFile(new URL('../../assets/shell.html', import.meta.url), 'utf8')
  assert.match(main, /function popupShellMenu\(request: ShellMenuPopupRequest\): Promise<void>/)
  assert.match(main, /menu\.once\('menu-will-close', close\)/)
  assert.match(main, /callback: close/)
  assert.match(shell, /function clearOpenMenu\(button=openMenu\)/)
  assert.match(shell, /try\{await api\.popupMenu\([\s\S]*?\)\}finally\{clearOpenMenu\(button\)\}/)
  assert.match(shell, /document\.addEventListener\('pointerdown',[\s\S]*?clearOpenMenu\(\)/)
  assert.doesNotMatch(shell, /:root\[data-color-scheme="light"\] \.menu:hover,:root\[data-color-scheme="light"\] \.menu\[aria-expanded="true"\]\{background/)
})

test('DSH 主题变化同步到桌面外壳、原生菜单和辅助窗口', async () => {
  const main = await readFile(new URL('../../src/main.ts', import.meta.url), 'utf8')
  const bridge = await readFile(new URL('../../src/desktop-bridge-client-source.ts', import.meta.url), 'utf8')
  const dshPreload = await readFile(new URL('../../src/dsh-view-preload.cts', import.meta.url), 'utf8')
  const shell = await readFile(new URL('../../assets/shell.html', import.meta.url), 'utf8')
  const settings = await readFile(new URL('../../assets/settings.html', import.meta.url), 'utf8')
  const shortcuts = await readFile(new URL('../../assets/shortcuts.html', import.meta.url), 'utf8')
  const about = await readFile(new URL('../../assets/about.html', import.meta.url), 'utf8')
  const startup = await readFile(new URL('../../assets/startup.html', import.meta.url), 'utf8')
  assert.doesNotMatch(bridge, /inject = \[[^\]]*'theme'/)
  assert.match(dshPreload, /reportDocumentTheme/)
  assert.match(dshPreload, /attributeFilter: \['style'\]/)
  assert.match(main, /nativeTheme\.themeSource = preference/)
  assert.match(main, /setTitleBarOverlay/)
  assert.match(shell, /\.bar\{[\s\S]*?background:var\(--chrome-surface\)/)
  assert.match(shell, /class="command-center" data-action="find"/)
  assert.match(main, /updateThemePreferences/)
  for (const source of [shell, settings, shortcuts, about, startup]) {
    assert.match(source, /data-color-scheme="light"/)
  }
  for (const source of [shell, settings, shortcuts, about]) assert.match(source, /dataset\.colorScheme=value\.colorScheme/)
  assert.match(main, /loadFile\(html, \{ query: desktopThemeQuery\(\) \}\)/)
})

test('运行时可通过 IPC 请求优雅重启，且复用唯一的重启交接实现', async () => {
  const source = await readFile(new URL('../../src/main.ts', import.meta.url), 'utf8')
  // 命中 app-restart 后必须复用既有 requestAppRestart（先调度分离实例再优雅关停），
  // 不允许出现第二条硬杀/自建重启路径。
  assert.match(source, /function isAppRestartIpc\(message: unknown\): boolean \{[\s\S]*?'type' in message[\s\S]*?APP_RESTART_IPC/)
  assert.match(source, /if \(isAppRestartIpc\(message\)\) \{[\s\S]*?runMainTask\(requestAppRestart\(\)\)/)
  assert.equal((source.match(/function requestAppRestart\(/g) ?? []).length, 1)
  assert.equal((source.match(/Stop-Process|process\.kill\(/g) ?? []).length, 0)
})

test('重启按钮宿主半侧提供受令牌保护的本机重启端点', async (t) => {
  const pluginDir = new URL('../../Data/DSH/profiles/web/local/dsh-restart-button/', import.meta.url)
  const hostPath = new URL('lib/index.js', pluginDir)
  if (!existsSync(hostPath)) {
    t.skip('实机插件产物缺失（CI 全新检出）')
    return
  }
  const host = await readFile(hostPath, 'utf8')
  const patch = await readFile(new URL('cordis.patch.yml', pluginDir), 'utf8')
  // 命名导出形态：模块级 inject 才生效，patch 条目只写 id/name/config。
  assert.match(host, /export const name = 'dsh-restart-button'/)
  assert.match(host, /export const inject = \['webServer'\]/)
  assert.match(host, /webServer\.register\(\{\s*kind: 'prefix'/)
  // 令牌未配置即整体停用；错误令牌必须被拒绝，不能有「无令牌放行」分支。
  assert.match(host, /token === '' \|\| req\.headers\['x-dsh-agent-token'\] !== token/)
  assert.match(host, /req\.method !== 'POST'/)
  // 只上报外壳，不自行关停进程。
  assert.match(host, /process\.send\?\.\(\{ type: 'app-restart' \}\)/)
  assert.doesNotMatch(host, /process\.exit\(|process\.kill\(/)
  assert.match(patch, /config:\s*\n\s*agentToken: '[0-9a-f]{64}'/)
})
test('Windows 窗口状态切换先冻结多层内容，稳定后重新布局再显示', async () => {
  const main = await readFile(new URL('../../src/main.ts', import.meta.url), 'utf8')
  assert.match(main, /let mainWindowContentSuppressed = false/)
  assert.match(main, /let mainWindowLayoutDeferred = false/)
  assert.match(main, /if \(mainWindowContentSuppressed\) \{[\s\S]*?setVisible\(false\)[\s\S]*?broadcastShellState\(\)/)
  assert.match(main, /if \(mainWindowLayoutDeferred\) \{[\s\S]*?broadcastShellState\(\)/)
  assert.match(main, /function installWindowSurfaceGuard\(window: BrowserWindow\): void \{[\s\S]*?process\.platform !== 'win32'/)
  assert.match(main, /const hideSurface = \(hideWindow = false\): void => \{[\s\S]*?if \(hideWindow\) \{[\s\S]*?window\.setOpacity\(0\)[\s\S]*?windowOpacitySuppressed = true[\s\S]*?\}[\s\S]*?setMainWindowContentVisible\(window, false\)/)
  assert.match(main, /window\.on\('minimize', \(\) => \{\s*hideSurface\(true\)/)
  assert.match(main, /window\.on\('restore', \(\) => \{[\s\S]*?hideSurface\(true\)[\s\S]*?revealSurfaceWhenStable\(32, true\)/)
  assert.match(main, /setMainWindowContentVisible\(window, true\)[\s\S]*?if \(restoreWindow \|\| windowOpacitySuppressed\) \{[\s\S]*?window\.setOpacity\(1\)/)
  assert.match(main, /mainWindowLayoutDeferred = true[\s\S]*?revealSurfaceWhenStable\(\)/)
  assert.match(main, /window\.on\('maximize', beginDisplayModeTransition\)/)
  assert.match(main, /window\.on\('unmaximize', beginDisplayModeTransition\)/)
  assert.match(main, /window\.on\('resized', \(\) => \{[\s\S]*?mainWindowContentSuppressed \|\| mainWindowLayoutDeferred[\s\S]*?revealSurfaceWhenStable\(32, mainWindowContentSuppressed\)/)
  assert.match(main, /installWindowSurfaceGuard\(window\)/)
})

test('重启按钮不会把未完成的重启伪装成已完成', async (t) => {
  const clientPath = new URL('../../Data/DSH/profiles/web/local/dsh-restart-button/lib/client.js', import.meta.url)
  if (!existsSync(clientPath)) {
    t.skip('实机插件客户端缺失（CI 全新检出）')
    return
  }
  const client = await readFile(clientPath, 'utf8')
  assert.match(client, /const RESTART_TIMEOUT_MS = 15_000/)
  assert.match(client, /state === "starting" \? RESTART_TIMEOUT_MS : 5000/)
  assert.match(client, /starting: "重启中"/)
  assert.match(client, /starting: "Restarting"/)
  assert.match(client, /failed: "重启失败"/)
  assert.match(client, /setState\("failed"\)/)
  assert.doesNotMatch(client, /setState\(s => s === "starting" \? "label" : s\)/)
})

test('浏览器工作区脚本引用的元素在它加载的每个文档里都存在', async () => {
  // browser-workspace.js 同时被 shell.html（外壳顶栏所在文档）与 browser-panel.html 加载。
  // 任一 byId 命中 null，create() 里紧跟的 addEventListener 就会抛错，而 shell.html 是在顶层
  // 调用 create()：整个内联脚本中断 ⇒ 菜单空白、返回/前进/搜索胶囊/重启/桌面设置/检查更新
  // 全部点不动（2026-09-13 实机故障：漏了 browser-menu-external 一个 id）。
  const workspace = await readFile(new URL('../../assets/browser-workspace.js', import.meta.url), 'utf8')
  const ids = [...new Set([...workspace.matchAll(/byId\(\s*'([^']+)'\s*\)/g)].map(match => match[1]))]
  assert.ok(ids.length > 40, `未解析到浏览器工作区元素 id（只解析出 ${ids.length} 个）`)
  for (const document of ['shell.html', 'browser-panel.html']) {
    const html = await readFile(new URL(`../../assets/${document}`, import.meta.url), 'utf8')
    const missing = ids.filter(id => !html.includes(`id="${id}"`))
    assert.deepEqual(missing, [], `${document} 缺少 browser-workspace.js 需要的元素：${missing.join(', ')}`)
  }
  assert.match(workspace, /elements\.menuExternal\?\.addEventListener\('click'/)
})
